0.8.0~rc1-4ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/lxc.postinst b/debian/lxc.postinst
--- a/debian/lxc.postinst
+++ b/debian/lxc.postinst
@@ -1,112 +1,74 @@
 #!/bin/sh
+# postinst script for lxc
+#
+# see: dh_installdeb(1)
 
 set -e
 
-. /usr/share/debconf/confmodule
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-_CONFFILE="/etc/default/lxc"
+add_users()
+{
+    if ! getent group lxc-dnsmasq >/dev/null; then
+        addgroup --quiet --system lxc-dnsmasq
+    fi
 
-case "${1}" in
-	configure)
-		db_get lxc/auto
-		LXC_AUTO="${RET}" # boolean
+    if ! getent passwd lxc-dnsmasq >/dev/null; then
+        adduser --quiet \
+            --system \
+	    --ingroup lxc-dnsmasq \
+            --quiet \
+            --disabled-login \
+            --disabled-password \
+	    --home /var/lib/lxc \
+            --no-create-home \
+            -gecos "LXC dnsmasq" \
+            lxc-dnsmasq
+    fi
+}
 
-		db_get lxc/shutdown
-		LXC_SHUTDOWN="${RET}" # select
+apparmor_load() {
+    # don't load profiles if mount mediation is not supported
+    SYSF=/sys/kernel/security/apparmor/features/mount/mask
+    if [ ! -f $SYSF ]; then
+        return
+    fi
 
-		db_get lxc/directory
-		LXC_DIRECTORY="${RET:-/var/lib/lxc}" # string (w/o empty)
+    if [ -x /lib/init/apparmor-profile-load ]; then
+        /lib/init/apparmor-profile-load lxc-containers
+    fi
+}
 
-		db_stop
+case "$1" in
+    configure)
+        add_users
+        apparmor_load
+    ;;
 
-		if [ ! -e "${_CONFFILE}" ]
-		then
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
 
-cat > "${_CONFFILE}" << EOF
-# /etc/default/lxc
-
-LXC_AUTO="${LXC_AUTO}"
-LXC_DIRECTORY="${LXC_DIRECTORY}"
-EOF
-		fi
-
-		cp -a -f "${_CONFFILE}" "${_CONFFILE}.tmp"
-
-		# If the admin deleted or commented some variables but then set
-		# them via debconf, (re-)add them to the config file.
-
-		test -z "${LXC_AUTO}" || \
-		grep -Eq '^ *LXC_AUTO=' "${_CONFFILE}" || \
-		echo "LXC_AUTO=" >> "${_CONFFILE}"
-
-		test -z "${LXC_DIRECTORY}" || \
-		grep -Eq '^ *LXC_DIRECTORY=' "${_CONFFILE}" || \
-		echo "LXC_DIRECTORY=" >> "${_CONFFILE}"
-
-		sed -e "s|^ *LXC_AUTO=.*|LXC_AUTO=\"${LXC_AUTO}\"|" \
-		    -e "s|^ *LXC_DIRECTORY=.*|LXC_DIRECTORY=\"${LXC_DIRECTORY}\"|" \
-		< "${_CONFFILE}" > "${_CONFFILE}.tmp"
-
-		mv -f "${_CONFFILE}.tmp" "${_CONFFILE}"
-
-		# Create lxc directories
-		for _DIRECTORY in "${LXC_DIRECTORY}" /etc/lxc/auto /etc/lxc/debconf /usr/share/lxc/cache /usr/share/lxc/packages /var/log/lxc
-		do
-			# Using ls to not fail on (temporarily) dangling symlinks
-			# which might be the sysadmins intention
-			if ! ls "${_DIRECTORY}" > /dev/null 2>&1
-			then
-				mkdir -p "${_DIRECTORY}"
-			fi
-		done
-
-		chmod 0700 /var/log/lxc
-
-		if [ "${LXC_DIRECTORY}" != "/var/lib/lxc" ]
-		then
-			if [ -h /var/lib/lxc ]
-			then
-				# Remove possibly old symlink
-				rm -f /var/lib/lxc
-			elif [ -e /var/lib/lxc ]
-			then
-				# Move old lxc directory
-				mv /var/lib/lxc /var/lib/lxc.orig
-			fi
-
-			ln -s "${LXC_DIRECTORY}" /var/lib/lxc
-		fi
-
-		# Handling lxc-shutdown alternative
-		update-alternatives --install \
-			/usr/bin/lxc-shutdown lxc-shutdown /usr/bin/lxc-stop 100 \
-			--slave /usr/share/man/man1/lxc-shutdown.1.gz lxc-shutdown.1.gz \
-				/usr/share/man/man1/lxc-stop.1.gz
-
-		update-alternatives --install \
-			/usr/bin/lxc-shutdown lxc-shutdown /usr/bin/lxc-halt 200 \
-			--slave /usr/share/man/man1/lxc-shutdown.1.gz lxc-shutdown.1.gz \
-				/usr/share/man/man1/lxc-halt.1.gz
-
-		# Migrate 0.7.5 to 0.8.0
-		if [ ! -e "${LXC_SHUTDOWN}" ] && [ -e "/usr/bin/lxc-${LXC_SHUTDOWN}" ]
-		then
-			LXC_SHUTDOWN="/usr/bin/lxc-${LXC_SHUTDOWN}"
-		fi
-
-		update-alternatives --quiet --set lxc-shutdown ${LXC_SHUTDOWN}
-		;;
-
-	abort-upgrade|abort-remove|abort-deconfigure)
-
-		;;
-
-	*)
-		echo "postinst called with unknown argument \`${1}'" >&2
-		exit 1
-		;;
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
 exit 0
+
+
