0.7.1-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/src/lxc/lxc-checkconfig.in b/src/lxc/lxc-checkconfig.in
--- a/src/lxc/lxc-checkconfig.in
+++ b/src/lxc/lxc-checkconfig.in
@@ -9,18 +9,24 @@ SETCOLOR_FAILURE="echo -en \\033[1;31m"
 SETCOLOR_WARNING="echo -en \\033[1;33m"
 SETCOLOR_NORMAL="echo -en \\033[0;39m"
 
+is_set() {
+    $GREP -q "$1=[y|m]" $CONFIG
+    return $?
+}
+
 is_enabled() {
     mandatory=$2
-    $GREP -q "$1=[y|m]" $CONFIG
+
+    is_set $1
     RES=$?
 
-    if [ $RES = 0 ]; then
+    if [ $RES -eq 0 ]; then
 	$SETCOLOR_SUCCESS && echo -e "enabled" && $SETCOLOR_NORMAL
     else
 	if [ ! -z "$mandatory" -a "$mandatory" = yes ]; then
-	    $SETCOLOR_FAILURE && echo -e "disabled" && $SETCOLOR_NORMAL
+	    $SETCOLOR_FAILURE && echo -e "required" && $SETCOLOR_NORMAL
 	else
-	    $SETCOLOR_WARNING && echo -e "disabled" && $SETCOLOR_NORMAL
+	    $SETCOLOR_WARNING && echo -e "missing" && $SETCOLOR_NORMAL
 	fi
     fi
 }
@@ -35,8 +41,10 @@ if [ ! -f $CONFIG ]; then
     GREP=grep
     if [ ! -f $CONFIG ]; then
         echo
-        echo "The kernel configuration can not be retrieved"
-        echo "Please recompile with IKCONFIG_PROC or install the kernel headers"
+        echo "The kernel configuration can not be retrieved."
+        echo "Please recompile with IKCONFIG_PROC, or"
+	echo "install the kernel headers, or specify"
+	echo "the path to the config file with: CONFIG=<path> lxc-checkconfig"
         echo
         exit 1
     else
@@ -54,16 +62,25 @@ echo -n "Network namespace: " && is_enabled CONFIG_NET_NS
 echo -n "Multiple /dev/pts instances: " && is_enabled DEVPTS_MULTIPLE_INSTANCES
 echo
 echo "--- Control groups ---"
-echo -n "Cgroup: " && is_enabled CONFIG_CGROUPS
+echo -n "Cgroup: " && is_enabled CONFIG_CGROUPS yes
 echo -n "Cgroup namespace: " && is_enabled CONFIG_CGROUP_NS
 echo -n "Cgroup device: " && is_enabled CONFIG_CGROUP_DEVICE
 echo -n "Cgroup sched: " && is_enabled CONFIG_CGROUP_SCHED
 echo -n "Cgroup cpu account: " && is_enabled CONFIG_CGROUP_CPUACCT
 echo -n "Cgroup memory controller: " && is_enabled CONFIG_CGROUP_MEM_RES_CTLR
-echo -n "Cgroup cpuset: " && is_enabled CONFIG_CPUSETS
+is_set CONFIG_SMP && echo -n "Cgroup cpuset: " && is_enabled CONFIG_CPUSETS
 echo
 echo "--- Misc ---"
 echo -n "Veth pair device: " && is_enabled CONFIG_VETH
 echo -n "Macvlan: " && is_enabled CONFIG_MACVLAN
 echo -n "Vlan: " && is_enabled CONFIG_VLAN_8021Q
-echo -n "File capabilities: " && is_enabled CONFIG_SECURITY_FILE_CAPABILITIES
+KVER_MINOR=$($GREP '^# Linux kernel version:' $CONFIG | \
+    sed -r 's/.*2.6.([0-9]{2}).*/\1/')
+[[ ${KVER_MINOR} < 33 ]] && echo -n "File capabilities: " && is_enabled \
+    CONFIG_SECURITY_FILE_CAPABILITIES
+
+echo
+echo "Note : Before booting a new kernel, you can check its configuration"
+echo "usage : CONFIG=/path/to/config $0"
+echo
+
